03-11-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtError al cargar la clave del certificadoCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\TapProd.crt                                                                               
.Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\TapProd.crt                                                                               
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\gestion.key                                                                               , J:\XSOFTSQL\PROYECTOS\TRANSPORTE\AfipCert\TapProd.crt                                                                               

05-01-2023 12:14:23 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado ws_sr_padron_a5WSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...20-30229993-6Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 200, in Consultar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 219, in call
  File "pysimplesoap\client.pyc", line 264, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "pysimplesoap\transport.pyc", line 133, in _conn_request
  File "pysimplesoap\transport.pyc", line 117, in _conn_request
  File "httplib2\__init__.pyc", line 1257, in _conn_request
  File "httplib2\__init__.pyc", line 1044, in connect
SSLHandshakeError: [SSL: SSLV3_ALERT.Llamada: PADRON.Consultar ERROR NO DEFINIDO
13-06-2023 14:01:46 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado ws_sr_padron_a5WSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...20-30229993-6Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 200, in Consultar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 466, in unmarshall
TypeError: Tag: esSucesion invalid (type not found)
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
13-06-2023 14:03:52 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...20-30229993-6Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 200, in Consultar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 466, in unmarshall
TypeError: Tag: esSucesion invalid (type not found)
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
13-06-2023 14:07:22 , Iniciando FeedBackWSSA Version 2.11c HomologaciónWSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.04_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...20-30229993-6Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 201, in Consultar
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 522, in unmarshall
  File "pysimplesoap\simplexml.pyc", line 466, in unmarshall
TypeError: Tag: esSucesion invalid (type not found)
.Llamada: PADRON.Consultar ERROR NO DEFINIDO
