23-05-2023 13:59:21 , REGPROCESO_SYNC4.INIT, Error: La sesión de datos nº 2 no se puede liberar si hay transacciones abiertas.;Linea : oSeteo = CREATEOBJECT("Custom");Error :       1549;Ultimo Alias Activo: CSRSUCURSAL;Ultimo registro:          1 ;DBF: C:\USERS\MARCO\APPDATA\LOCAL\TEMP\0000HY4P01KI.TMP;Ultimo Control activo: 
23-05-2023 13:59:21 , Pila de llamadas
23-05-2023 13:59:21 , Programa    : j:\xsoftsql\proyectos\hernan\forms\sync\regproceso_sync4.sct
23-05-2023 13:59:21 , Objeto      : regproceso_sync4.init
23-05-2023 13:59:21 , Base Objeto : j:\xsoftsql\proyectos\hernan\forms\sync\regproceso_sync4.sct
23-05-2023 13:59:22 , Nº de Linea :          2
23-05-2023 13:59:22 , En el Fuente: this.iniciarseteos()
23-05-2023 13:59:22 , Programa    : j:\xsoftsql\proyectos\hernan\forms\sync\regproceso_sync4.sct
23-05-2023 13:59:22 , Objeto      : regproceso_sync4.iniciarseteos
23-05-2023 13:59:22 , Base Objeto : j:\xsoftsql\proyectos\hernan\forms\sync\regproceso_sync4.sct
23-05-2023 13:59:22 , Nº de Linea :         22
23-05-2023 13:59:22 , En el Fuente: this.leerconfiguracion(1)
23-05-2023 13:59:22 , Programa    : j:\xsoftsql\proyectos\hernan\forms\sync\regproceso_sync4.sct
23-05-2023 13:59:22 , Objeto      : regproceso_sync4.leerconfiguracion
23-05-2023 13:59:22 , Base Objeto : j:\xsoftsql\proyectos\hernan\forms\sync\regproceso_sync4.sct
23-05-2023 13:59:22 , Nº de Linea :          4
23-05-2023 13:59:22 , En el Fuente: 	oSeteo = CREATEOBJECT("Custom")
23-05-2023 13:59:22 , Fin
