27-03-2020 13:08:28 , PIDOLISTCTACTE.INIT, Error: La referencia al subíndice no es válida.;Linea : thisform.llenaroptiongroup(i,aListados[]);Error :         31;Ultimo Alias Activo: CSRSETEO;Ultimo registro:          1 ;DBF: C:\USERS\MARCO\APPDATA\LOCAL\TEMP\0000B9XL04J4.TMP;Ultimo Control activo: 
27-03-2020 13:08:28 , Pila de llamadas
27-03-2020 13:08:28 , Programa    : j:\xsoftsql\proyectos\comercial\forms\ventas\pidolistctacte.sct
27-03-2020 13:08:28 , Objeto      : pidolistctacte.init
27-03-2020 13:08:28 , Base Objeto : j:\xsoftsql\proyectos\comercial\forms\ventas\pidolistctacte.sct
27-03-2020 13:08:28 , Nº de Linea :         29
27-03-2020 13:08:28 , En el Fuente: thisform.llenaroptiongroup(i,aListados[])
27-03-2020 13:08:28 , Fin
