22-09-2016 , Version 2.11a InstallDir C:\ARCHIV~1\PyAfipWs1.18a C:\ARCHIV~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
Linea de codigo de error: Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
.Exepción: ResponseNotReady
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady

22-09-2016 , Version 2.11a InstallDir C:\ARCHIV~1\PyAfipWs1.18a C:\ARCHIV~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
Linea de codigo de error: Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady
.Exepción: ResponseNotReady
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 120, in Dummy
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 216, in call
  File "pysimplesoap\client.pyc", line 261, in send
  File "httplib2\__init__.pyc", line 1593, in request
  File "httplib2\__init__.pyc", line 1335, in _request
  File "httplib2\__init__.pyc", line 1291, in _conn_request
  File "httplib.pyc", line 1119, in getresponse
ResponseNotReady

26-05-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
.Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
27-09-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(0,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
11001: Campo CbteTipo, no es un tipo de comprobante valido. Ver metodo FEParamGetTiposCbte
27-09-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(0,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
11001: Campo CbteTipo, no es un tipo de comprobante valido. Ver metodo FEParamGetTiposCbte
02-10-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,7)Fecha Ulti: 02-10-2017Llamada: WSFE.CAESolicitarOrden:11000005731210051: Los importes informados en AlicIVA no se corresponden con los porcentajes.Llamada: WSFE.CAESolictar 602: No existen datos en nuestros registros para los parametros ingresados.
30-10-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
30-10-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,3)11002: El punto de venta no se encuentra habilitado a usar en el presente WS. Ver metodo FEParamGetPtosVenta
30-10-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,178)Fecha Ulti: 30-10-2017Llamada: WSFE.CAESolicitarOrden:11000005791810051: Los importes informados en AlicIVA no se corresponden con los porcentajes.Llamada: WSFE.CAESolictar 602: No existen datos en nuestros registros para los parametros ingresados.
30-10-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,178)Fecha Ulti: 30-10-2017Llamada: WSFE.CAESolicitarOrden:11000005791910044: El campo ImpOpEx (importe exento) no puede ser menor a cero (0).Llamada: WSFE.CAESolictar 602: No existen datos en nuestros registros para los parametros ingresados.
30-10-2017 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,2)Fecha Ulti: 03-10-2017Llamada: WSFE.CAESolicitarOrden:11000005792010046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitarLlamada: WSFE.CAESolictar 10046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,3)Fecha Ulti: 23-11-2017Llamada: WSFE.CAESolicitarOrden:11000005956510051: Los importes informados en AlicIVA no se corresponden con los porcentajes.Llamada: WSFE.CAESolictar 602: No existen datos en nuestros registros para los parametros ingresados.
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,3)Fecha Ulti: 23-11-2017Orden:11000005956510051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,3)Fecha Ulti: 23-11-2017Orden:11000005956510051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,3)Fecha Ulti: 23-11-2017Orden:11000005955110051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,4)Fecha Ulti: 02-01-2018Orden:11000005955110051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,4)Fecha Ulti: 02-01-2018Orden:11000005955110051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
02-01-2018 , Version 2.11a InstallDir C:\PROGRA~1\PyAfipWs1.18a C:\PROGRA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,5,4)Fecha Ulti: 02-01-2018Orden:11000005955110051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
10024: Si ImpTrib es mayor a 0 el objeto Tributos y Tributo son obligatorios.602: No existen datos en nuestros registros para los parametros ingresados.
31-01-2018 , WSFE.CompUltimoAutorizado(1,5)
31-01-2018 , WSFE.CompUltimoAutorizado(1,5)Codigo error afip:*****Numero de Error: 1924Linea de codigo de error: UltCBTE = WSFE.CompUltimoAutorizado(cTipoCbte, cPrefijo)Procedimiento: sw_ultimocomprobaError VFP: WSFE no es un objeto.
31-01-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,929)Fecha Ulti: 31-01-2018Orden:11000006180610016: El nÃºmero o fecha del comprobante no se corresponde con el prÃ³ximo a autorizar. Consultar metodo FECompUltimoAutorizado.10016: El nÃºmero o fecha del comprobante no se corresponde con el prÃ³ximo a autorizar. Consultar metodo FECompUltimoAutorizado.
31-01-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,930)Fecha Ulti: 31-01-2018Orden:11000006180610061: La suma de los campos BaseImp en AlicIva debe ser igual al valor ingresado en ImpNeto.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 9998
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410048: El campo  'Importe Total' ImpTotal, debe ser igual  a la  suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.
10051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410045: El campo ImpNeto (Importe neto  gravado) no puede ser menor a cero (0).
10048: El campo  'Importe Total' ImpTotal, debe ser igual  a la  suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.
10051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410048: El campo  'Importe Total' ImpTotal, debe ser igual  a la  suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.
10051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
10024: Si ImpTrib es mayor a 0 el objeto Tributos y Tributo son obligatorios.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
10024: Si ImpTrib es mayor a 0 el objeto Tributos y Tributo son obligatorios.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
10024: Si ImpTrib es mayor a 0 el objeto Tributos y Tributo son obligatorios.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
07-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,608)Fecha Ulti: 07-02-2018Orden:11000006241410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
08-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,996)Fecha Ulti: 07-02-2018Orden:11000006248310061: La suma de los campos BaseImp en AlicIva debe ser igual al valor ingresado en ImpNeto.602: No existen datos en nuestros registros para los parametros ingresados.
09-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,611)Fecha Ulti: 08-02-2018Codigo error afip:0Numero de Error: 1429Linea de codigo de error: cCAESolicitar = WSFE.CAESolicitar()Procedimiento: lote_procesoError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsfev1.pyc", line 265, in CAESolicitar
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1199). ---> Input string was not in a correct format.
.Exepción: Traceback: Server was unable to read request. ---> There is an error in XML document (5, 1199). ---> Input string was not in a correct format.
20-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,1061)Fecha Ulti: 20-02-2018Orden:11000006336710061: La suma de los campos BaseImp en AlicIva debe ser igual al valor ingresado en ImpNeto.602: No existen datos en nuestros registros para los parametros ingresados.
20-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

20-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: wsfe.SetTicketAcceso(ta)Procedimiento: sw_conectarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!
.Exepción: RuntimeError: Ticket de Acceso vacio!
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "utils.pyc", line 378, in SetTicketAcceso
RuntimeError: Ticket de Acceso vacio!

20-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OK
20-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: soapenv:Server.userException: javax.ejb.EJBTransactionRolledbackException: Transaction rolled back
.Exepción: soapenv:Server.userException: javax.ejb.EJBTransactionRolledbackException: Transaction rolled backTraceback: 
20-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWsCodigo error afip:0Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: soapenv:Server.userException: javax.ejb.EJBTransactionRolledbackException: Transaction rolled back
.Exepción: soapenv:Server.userException: javax.ejb.EJBTransactionRolledbackException: Transaction rolled backTraceback: 
27-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,1109)Fecha Ulti: 27-02-2018Orden:110000062204
27-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,1109)Fecha Ulti: 27-02-2018Orden:11000006220410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.602: No existen datos en nuestros registros para los parametros ingresados.
27-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,1109)Fecha Ulti: 27-02-2018Orden:11000006220410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
27-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,1109)Fecha Ulti: 27-02-2018Orden:11000006220410051: Los importes informados en AlicIVA no se corresponden con los porcentajes.
27-02-2018 , Version 2.11a InstallDir C:\APLICA~1\PyAfipWs1.18a C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,4,1109)Fecha Ulti: 27-02-2018Orden:11000006220410043: El campo ImpTotConc (Importe neto no gravado) no puede ser menor a cero (0).
25-06-2019 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionError al cargar el certificado crtCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\COMERCIAL\AfipCert\Gestion.key                                       , J:\XSOFTSQL\PROYECTOS\COMERCIAL\AfipCert\Cachitos.crt                                      
..Exepción: RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\COMERCIAL\AfipCert\Gestion.key                                       , J:\XSOFTSQL\PROYECTOS\COMERCIAL\AfipCert\Cachitos.crt                                      
Traceback: Traceback (most recent call last):
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "wsaa.pyc", line 258, in SignTRA
  File "wsaa.pyc", line 96, in sign_tra
RuntimeError: Archivos no encontrados: J:\XSOFTSQL\PROYECTOS\COMERCIAL\AfipCert\Gestion.key                                       , J:\XSOFTSQL\PROYECTOS\COMERCIAL\AfipCert\Cachitos.crt                                      

30-07-2019 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\PROGRA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5824:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5824:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5824:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

.Exepción: SMIME_Error: 5824:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5824:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5824:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 5824:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
5824:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
5824:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


20-08-2019 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

..Exepción: SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


20-08-2019 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

..Exepción: SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


20-08-2019 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: cms = WSAA.SignTRA(tra, cRuta + this.pcrt, cRuta + this.pkey) && Cert. DemoProcedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

..Exepción: SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 250, in SignTRA
  File "wsaa.pyc", line 102, in sign_tra
  File "M2Crypto\SMIME.pyc", line 204, in sign
SMIME_Error: 4532:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:.\crypto\x509\x509_cmp.c:328:
4532:error:2108907F:PKCS7 routines:PKCS7_sign_add_signer:private key does not match certificate:.\crypto\pkcs7\pk7_smime.c:163:
4532:error:21074099:PKCS7 routines:PKCS7_sign:pkcs7 add signer error:.\crypto\pkcs7\pk7_smime.c:87:


20-08-2019 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
29-01-2020 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
29-01-2020 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
29-01-2020 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
29-01-2020 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
29-01-2020 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
29-01-2020 , Iniciando FeedBackWSSA Version 2.11a WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TACodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ta = WSAA.LoginCMS(cms)Procedimiento: sw_wsaa_iniciarError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 151, in capturar_errores_wrapper
  File "wsaa.pyc", line 255, in LoginCMS
  File "pysimplesoap\client.pyc", line 147, in <lambda>
  File "pysimplesoap\client.pyc", line 342, in wsdl_call
  File "pysimplesoap\client.pyc", line 220, in call
SoapFault: ns1:cms.cert.expired: Certificado expirado
..Exepción: ns1:cms.cert.expired: Certificado expiradoTraceback: 
06-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,20)Fecha Ulti: 06-03-2020Orden:11000007310810043: El campo ImpTotConc (Importe neto no gravado) no puede ser menor a cero (0).
10046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar10043: El campo ImpTotConc (Importe neto no gravado) no puede ser menor a cero (0).
10046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar
06-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,20)Fecha Ulti: 06-03-2020Orden:11000007310810043: El campo ImpTotConc (Importe neto no gravado) no puede ser menor a cero (0).
10046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar10043: El campo ImpTotConc (Importe neto no gravado) no puede ser menor a cero (0).
10046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar
06-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,20)Fecha Ulti: 06-03-2020Orden:11000007310810046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar10046: El campo ImpTrib (Importe de tributos) no puede ser menor a cero (0).
500: Error interno de aplicación: - Metodo FECAESolicitar
06-03-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,0)11000: Campo PtoVta, no es un punto de venta valido, los valores posibles son entre 1 y 99998
29-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,993)Fecha Ulti: 29-10-2020Llamada: WSFE.CAESolicitarOrden:11000009430910020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
29-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,993)Fecha Ulti: 29-10-2020Llamada: WSFE.CAESolicitarOrden:11000009431110020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
29-10-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(1,5,994)Fecha Ulti: 29-10-2020Orden:11000009431610020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.
06-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado wsfeWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(8,5)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(8,5,40)Fecha Ulti: 08-02-2021Llamada: WSFE.CrearFacturaCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = WSFE.AgregarCmpAsoc(ntipo, nprefijo, nNumComp, cCuitAso,sFecha)Procedimiento: solicitar_procesoError VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
TypeError: AgregarCmpAsoc() takes at most 4 arguments (6 given)
..Exepción: Traceback: 
06-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.18a WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OK
12-04-2021 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSFE Version 1.23b WSFE InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSFEConexxion Existosaappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(6,4)Consultamos la fecha del ultimo comprobanteWSFE.CompConsultar(6,4,315)Fecha Ulti: 05-04-2021ERROR AL SOLICITARCAEEl nro de comprobante autorizado1 ya se encontraba informado.El ultimo autorizado por Afip es315El Total consultado (79.99)no coincide con el del comprobante (1.00)
