26-02-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsCertificados ProduccionSolicitando TATA Almacenado ws_sr_padron_a5WSSrPadronA5 1.03_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...27-15265265-3Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 212, in Consultar
KeyError: 'error'
..Llamada: PADRON.Consultar ERROR NO DEFINIDO
26-02-2020 , Iniciando FeedBackWSSA Version 2.11c WSSA InstallDir C:\APLICA~1\PyAfipWsTA recuperadoWSSrPadronA5 1.03_2e WSSrPadronA5 InstallDir C:\APLICA~1\PyAfipWsEnviando TAConectando al servicio WSSrPadronA5Conexion ExistosaConsultando AFIP online...27-15265265-3Llamada: PADRON.ConsultarCodigo error afip:*****Numero de Error: 1429Linea de codigo de error: ok = PADRON.Consultar(cDocumento)Procedimiento: cuit_proceso_2Error VFP: OLE IDispatch exception code 0 from Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 158, in capturar_errores_wrapper
  File "ws_sr_padron.pyc", line 212, in Consultar
KeyError: 'error'
..Llamada: PADRON.Consultar ERROR NO DEFINIDO
