06-04-2019 , soap:Server: No se pudo verificar que <sign> contenga una firma valida de <token>Error number: 1429Error message: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _invoke_
  FiLine of code with error: ok = PADRON.Consultar(cDocumento)Line number of error: 80Program with error: ERRHAND3
